language: go

matrix:
  include:
    - os: linux
      go: 1.9.1
    - os: linux
      go: tip
    - os: osx
      osx_image: xcode8.3
      go: 1.9.1
    - os: osx
      osx_image: xcode8.3
      go: tip

script:
  - go vet -v ./...
  - make test

notifications:
  email:
    # we can see the result on GitHub :)
    on_success: never
    # notify only first failure
    on_failure: change
