language: go

go:
  - 1.9.1
  - tip

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3

script:
  - go vet -v ./...
  - make test

notifications:
  email:
    # we can see the result on GitHub :)
    on_success: never
    # notify only first failure
    on_failure: change
